export enum WasteType {
  PLASTIC = 'PLASTIC',
  PAPER = 'PAPER',
  GLASS = 'GLASS',
  METAL = 'METAL',
  ELECTRONICS = 'ELECTRONICS',
  ORGANIC = 'ORGANIC',
  OTHER = 'OTHER'
}

export enum CollectionStatus {
  PENDING = 'PENDING',
  OCCUPIED = 'OCCUPIED',
  IN_PROGRESS = 'IN_PROGRESS',
  VALIDATED = 'VALIDATED',
  REJECTED = 'REJECTED'
}
